"""SIM 7 runner: sim-coverage audit of the FINAL V2 values.

Every case is its own netlist (generated from a sim7_*.cir template into sim7_runs/) and its
own LTspice process, with a hard timeout and a no-CPU-progress watchdog, so one stuck case
cannot block the rest.  Pattern follows sim5_run_split.py (fresh-log check, UTF-16 log
decoding, .meas parsing).  Only PIDs started here are ever killed.

Usage:  python sim7_run.py [group ...]
        groups: mon out ls chain1 chain2 ctran osc osc2 nocs  (default: all; chain2/ctran need chain1)
        only:<name-substring>,<group>[,<first opfix index>]   re-runs a subset of one group
Results are merged into sim7_results.json (one entry per case, saved as each case finishes).
Tables: python sim7_report.py (see sim7_README.md).
"""
import re, os, sys, json, time, subprocess, itertools
from concurrent.futures import ThreadPoolExecutor, as_completed
try:
    import psutil
except ImportError:
    psutil = None

HERE = os.path.dirname(os.path.abspath(__file__))
SIMS = os.path.dirname(HERE)
RUNS = os.path.join(HERE, "sim7_runs")
LT = r"C:\Users\lawre\AppData\Local\Programs\ADI\LTspice\LTspice.exe"
TIMEOUT = 240          # hard limit per case (s)
STALL = 60             # watchdog: kill if the process used no CPU for this long (s)
WORKERS = 4
RESULTS = os.path.join(HERE, "sim7_results.json")
os.makedirs(RUNS, exist_ok=True)


# ---------------------------------------------------------------- netlist generation
def _abs_includes(txt):
    def rep(m):
        name = m.group(1).strip()
        if name.startswith("../"):
            return ".include " + os.path.join(SIMS, name[3:]).replace("\\", "/")
        if name.endswith(".inc"):                       # inline local include files
            inc = open(os.path.join(HERE, name), encoding="utf-8").read()
            return "* ---- inlined " + name + " ----\n" + _abs_includes(inc) + "\n* ---- end " + name + " ----"
        return m.group(0)
    return re.sub(r"^\.include\s+(\S+)\s*$", rep, txt, flags=re.M | re.I)


# .op retry settings for the full-chain netlists (the LM8261/NE5532 macro-model .op search is
# erratic: the same netlist may converge in 5 s or give up after 140 s).  Only documented LTspice
# options are used (noopiter / gminsteps / srcstepmethod all appear in LTspice's own .op log).
FIXES = [
    ("none", None, None),
    ("srcstep1", "noopiter gminsteps=0 srcstepmethod=1", None),
    ("noopiter", "noopiter", None),
    ("gq3-0.05", "noopiter gminsteps=0", ("V(gq3)={VTQ3+0.1}", "V(gq3)={VTQ3-0.05}")),
    ("nonodeset", None, "STRIP_NODESETS"),
]
# the two full-chain templates use their own start-up routes (see the START-UP note in them)
CHAIN_FIXES = [
    ("op", None, None),
    ("hv0_150", None, "HV0=150"),
    ("startup", None, "STARTUP"),
    ("hv0_150+srcstep1", "noopiter gminsteps=0 srcstepmethod=1", "HV0=150"),
]
CHAIN_TEMPLATES = ("sim7_chain_dc.cir", "sim7_chain_tran.cir")
ATTEMPT_TIMEOUT = {"sim7_chain_dc.cir": 90}
RETRY_TEMPLATES = ("sim7_chain_dc.cir", "sim7_chain_tran.cir", "sim7_out_sine.cir", "sim7_out_step.cir",
                   "sim7_out_loop.cir", "sim7_ls_ac.cir", "sim7_ls_step.cir", "sim7_ls_sine.cir")


def fixes_for(template):
    return CHAIN_FIXES if template in CHAIN_TEMPLATES else FIXES


def make(template, name, params=None, gear=False, fix=0, nocs=False):
    txt = open(os.path.join(HERE, template), encoding="utf-8").read()
    txt = _abs_includes(txt)
    for k, v in (params or {}).items():
        pat = re.compile(r"^(\.param\b.*?\s)" + re.escape(k) + r"=\S+", re.M)
        txt, n = pat.subn(lambda m: m.group(1) + f"{k}={v}", txt, count=1)
        if n != 1:
            raise ValueError(f"{template}: .param {k} not found")
    if gear:
        txt = re.sub(r"^(\.options\b)", r"\1 method=gear", txt, count=1, flags=re.M)
    if nocs:                         # drop Sim 2's 'cshunt=1e-12' (1 pF on EVERY node, incl. op-amp internals)
        txt, n = re.subn(r"^(\.options\b.*?)\s+cshunt=\S+", r"\1", txt, flags=re.M)
        assert n >= 1, template + ": no cshunt to remove"
    fname, fopt, frep = fixes_for(template)[fix]
    if fopt:
        txt = re.sub(r"^(\.options\b)", r"\1 " + fopt, txt, count=1, flags=re.M)
    if frep in ("STRIP_NODESETS", "STARTUP"):
        txt = re.sub(r"^\.nodeset\b.*$", "* (nodeset removed by opfix)", txt, flags=re.M)
        if frep == "STARTUP":
            txt = re.sub(r"^(\.tran\b.*)$", r"\1 startup", txt, count=1, flags=re.M)
    elif frep == "HV0=150":
        txt, n = re.subn(r"^\.param HV0=\S+", ".param HV0=150", txt, count=1, flags=re.M)
        assert n == 1
    elif frep and frep[0] in txt:
        txt = txt.replace(*frep)
    txt = f"* generated by sim7_run.py from {template}  params={params}  gear={gear}  opfix={fname}  nocshunt={nocs}\n" + txt
    path = os.path.join(RUNS, f"sim7_{name}.cir")
    open(path, "w", encoding="utf-8").write(txt)
    return dict(name=name, path=path, template=template, params=params or {}, gear=gear, fix=fix, nocs=nocs)


# ---------------------------------------------------------------- log parsing
NUM = r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?"

def parse_log(txt):
    res, fails, steps = {}, [], {}
    for line in txt.splitlines():
        m = re.match(r"^(\w+):\s+(.*)$", line)
        if m and m.group(1).lower() not in ("measurement", "circuit", "options", "files", "warning", "solver"):
            key, rest = m.group(1).lower(), m.group(2)
            if "FAIL" in rest.upper():
                fails.append(key); continue
            c = re.search(r"=\(\s*(" + NUM + r")dB,\s*(" + NUM + r")", rest)
            if c:
                res[key + "_db"] = float(c.group(1)); res[key + "_deg"] = float(c.group(2)); continue
            v = re.search(r"=\s*(" + NUM + r")", rest)
            if v:
                res[key] = float(v.group(1))
            a = re.search(r"\sAT\s+(" + NUM + r")\s*$", rest, re.I)     # WHEN results: the crossing point
            if a:
                res[key + "_at"] = float(a.group(1))
    # stepped tables:  "Measurement: name" / header / rows "  i  value ..."
    for blk in re.finditer(r"Measurement:\s*(\w+)\s*\n[^\n]*\n((?:\s+\d+\s+[^\n]*\n)+)", txt):
        vals = []
        for row in blk.group(2).splitlines():
            parts = row.split()
            if len(parts) >= 2:
                c = re.match(r"\(\s*(" + NUM + r")dB", parts[1])
                vals.append(float(c.group(1)) if c else (float(parts[1]) if re.fullmatch(NUM, parts[1]) else parts[1]))
        steps[blk.group(1).lower()] = vals
    for m in re.finditer(r"Measurement \"?(\w+)\"? FAIL", txt, re.I):
        fails.append(m.group(1).lower())
    thd = re.findall(r"Total Harmonic Distortion:\s*(" + NUM + r")%", txt)
    if thd:
        res["thd_pct"] = float(thd[-1])
    if steps:
        res["_steps"] = steps
    return res, sorted(set(fails))


# ---------------------------------------------------------------- running
def _rm(fn, tries=10):
    """Delete a scratch file; tolerate a short lock (LTspice just exiting, OneDrive sync)."""
    for _ in range(tries):
        try:
            os.remove(fn); return True
        except FileNotFoundError:
            return True
        except PermissionError:
            time.sleep(0.5)
    return False


def run(job):
    path = job["path"]; base = path[:-4]
    for ext in (".log", ".raw", ".op.raw"):
        _rm(base + ext)
    t0 = time.time()
    p = subprocess.Popen([LT, "-b", path], cwd=RUNS)
    status, last_cpu, last_prog = "ok", -1.0, time.time()
    while True:
        try:
            p.wait(timeout=2); break
        except subprocess.TimeoutExpired:
            pass
        now = time.time()
        if now - t0 > ATTEMPT_TIMEOUT.get(job["template"], TIMEOUT):
            status = "TIMEOUT"; break
        if psutil:
            try:
                ct = psutil.Process(p.pid).cpu_times(); cpu = ct.user + ct.system
                if cpu > last_cpu + 0.05:
                    last_cpu, last_prog = cpu, now
                elif now - last_prog > STALL:
                    status = "HUNG (no CPU progress)"; break
            except psutil.NoSuchProcess:
                pass
    if p.poll() is None:                     # kill only what we started (+ its children)
        if psutil:
            try:
                for ch in psutil.Process(p.pid).children(recursive=True):
                    ch.kill()
            except psutil.NoSuchProcess:
                pass
        p.kill(); p.wait()
    dt = time.time() - t0
    res, fails, err = {}, [], ""
    log = base + ".log"
    if os.path.exists(log) and os.path.getmtime(log) >= t0 - 1:      # freshness check
        raw = open(log, "rb").read()
        txt = raw.decode("utf-16-le", errors="ignore") if b"\x00" in raw[:200] else raw.decode("latin-1")
        res, fails = parse_log(txt)
        e = re.findall(r"^(.*(?:[Ee]rror|singular|Timestep too small|convergence failed)[^\n]*)$", txt, re.M)
        err = " | ".join(e[:3])
        if status == "ok" and re.search(r"skipping operating point|Trouble finding operating point", txt, re.I):
            status = "OP FAILED"          # transient would have started from an all-zero state
        if status == "ok" and not res:
            status = "NO MEASUREMENTS"
    elif status == "ok":
        status = "NO FRESH LOG"
    for ext in (".raw", ".op.raw"):
        _rm(base + ext)
    with open(os.path.join(HERE, "sim7_progress.txt"), "a") as f:
        f.write(f"{time.strftime('%H:%M:%S')} {job['name']} {status} {dt:.1f}s\n")
    return job["name"], dict(status=status, t=round(dt, 1), template=job["template"],
                             params=job["params"], gear=job["gear"], nocshunt=job.get("nocs", False), opfix=fixes_for(job["template"])[job.get("fix", 0)][0],
                             meas=res, fails=fails, err=err)


def _one(job):
    """Run a case; for the chain templates retry with the next .op fix until one works."""
    history = []
    while True:
        name, r = run(job)
        history.append(f"{r['opfix']}:{r['status']}")
        if r["status"] == "ok" or job["template"] not in RETRY_TEMPLATES or job["fix"] + 1 >= len(fixes_for(job["template"])):
            r["tries"] = history
            return name, r
        job = make(job["template"], name, job["params"], job["gear"], fix=job["fix"] + 1, nocs=job.get("nocs", False))


def run_all(jobs):
    """Run all jobs; each result is saved to sim7_results.json as soon as it arrives, so an
    interrupted batch keeps everything that finished (the save runs in this thread only)."""
    out = {}
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futs = [ex.submit(_one, j) for j in jobs]
        for fut in as_completed(futs):
            try:
                name, r = fut.result()
            except Exception as e:                      # never lose the rest of the batch
                print("CASE CRASHED:", repr(e), flush=True); continue
            out[name] = r
            save({name: r})
            print(f"{name:40s} {r['status']:10s} {r['t']:6.1f}s  {' > '.join(r['tries'])}", flush=True)
    return out


def load():
    try: return json.load(open(RESULTS))
    except (FileNotFoundError, json.JSONDecodeError): return {}


def save(res):
    allr = load(); allr.update(res)
    json.dump(allr, open(RESULTS, "w"), indent=1, sort_keys=True)


# ---------------------------------------------------------------- case groups
def g_mon():
    return [make("sim7_mon_fault.cir", "mon_fault_22k", {"R30V": "22k"}),
            make("sim7_mon_powerdown.cir", "mon_pd_22k", {"R30V": "22k"}),
            make("sim7_mon_fault.cir", "mon_fault_10k", {"R30V": "10k"}),       # = Sim 4 repro
            make("sim7_mon_powerdown.cir", "mon_pd_10k", {"R30V": "10k"})]


VDC = {150: (0.15, 1.125, 2.1), 50: (0.05, 0.375, 0.7)}

def g_out():
    j = []
    for hv, cl in itertools.product((150, 50), ("10p", "22p", "47p", "100p")):
        j.append(make("sim7_out_sine.cir", f"out_sine_{hv}_{cl}", {"HV": hv, "CL": cl}))
    j.append(make("sim7_out_sine.cir", "out_sine_150_22p_cz100", {"HV": 150, "CL": "22p", "Cz": "100p"}))
    j.append(make("sim7_out_sine.cir", "out_sine_150_20p_r50", {"HV": 150, "CL": "20p", "R22V": 50}))  # Sim 2 value
    for hv in (150, 50):
        cls = ("10p", "47p", "100p") if hv == 150 else ("22p",)
        for vdc, cl in itertools.product(VDC[hv], cls):
            j.append(make("sim7_out_step.cir", f"out_step_{hv}_{vdc}_{cl}", {"HV": hv, "VDC": vdc, "CL": cl}))
            j.append(make("sim7_out_loop.cir", f"out_loop_{hv}_{vdc}_{cl}", {"HV": hv, "VDC": vdc, "CL": cl}))
    j.append(make("sim7_out_step.cir", "out_step_150_1.125_47p_cz100", {"HV": 150, "VDC": 1.125, "CL": "47p", "Cz": "100p"}))
    j.append(make("sim7_out_step.cir", "out_step_150_1.125_100p_gear", {"HV": 150, "VDC": 1.125, "CL": "100p"}, gear=True))
    j.append(make("sim7_out_loop.cir", "out_loop_150_0.75_22p_r50", {"HV": 150, "VDC": 0.75, "CL": "22p", "R22V": 50}))
    return j


def g_ls():
    j = []
    for hv, vbs in ((150, (-1.24, 0, 1.25)), (50, (-1.24, 0, 0.4))):
        for vb in vbs:
            j.append(make("sim7_ls_ac.cir", f"ls_ac_{hv}_{vb}", {"HV": hv, "VB": vb}))
            j.append(make("sim7_ls_step.cir", f"ls_step_{hv}_{vb}", {"HV": hv, "VB": vb}))
    j.append(make("sim7_ls_ac.cir", "ls_ac_50_0_r100k", {"HV": 50, "VB": 0, "R29V": "100k"}))   # = Sim 3 repro
    for hv, amp in ((150, 1.24), (120, 1.24), (50, 0.45), (50, 1.24)):
        j.append(make("sim7_ls_sine.cir", f"ls_sine_{hv}_{amp}", {"HV": hv, "AMP": amp}))
    return j


CHAIN_NOM = [(x2, vt) for x2 in (290, 500) for vt in (-2, -3, -4)]
SENS = {"r30_10k": {"R30V": "10k"}, "ib800n": {"IBX": "0.3u"}}

def cname(kind, hv, x2, vt, tag=""):
    return f"chain_{kind}_{hv}_x{x2}_v{abs(vt)}" + (f"_{tag}" if tag else "")

def g_chain1():
    j = []
    for (x2, vt), hv in itertools.product(CHAIN_NOM, (50, 120, 150)):
        j.append(make("sim7_chain_dc.cir", cname("trim", hv, x2, vt), {"HV": hv, "X2": x2, "VTQ3": vt, "MODE": 1}))
    for x2, hv in itertools.product((0, 1000), (50, 150)):
        j.append(make("sim7_chain_dc.cir", cname("trim", hv, x2, -3), {"HV": hv, "X2": x2, "VTQ3": -3, "MODE": 1}))
    for tag, extra in SENS.items():
        for hv in (50, 150):
            j.append(make("sim7_chain_dc.cir", cname("trim", hv, 290, -3, tag),
                          dict({"HV": hv, "X2": 290, "VTQ3": -3, "MODE": 1}, **extra)))
    return j


def _rc(allr, name):
    r = allr.get(name, {})
    return r.get("meas", {}).get("rc") if r.get("status") == "ok" else None

def g_chain2():
    allr, j = load(), []
    combos = [(x2, vt, "", {}) for x2, vt in CHAIN_NOM] + [(290, -3, t, e) for t, e in SENS.items()]
    for x2, vt, tag, extra in combos:
        for trim_hv, run_hvs in ((150, (50, 120)), (50, (120, 150))):
            if tag and trim_hv == 150: run_hvs = (50,)
            if tag and trim_hv == 50: run_hvs = (150,)
            rc = _rc(allr, cname("trim", trim_hv, x2, vt, tag))
            if rc is None:
                print("skip (no trim result):", cname("trim", trim_hv, x2, vt, tag)); continue
            for hv in run_hvs:
                j.append(make("sim7_chain_dc.cir", cname(f"fix{trim_hv}", hv, x2, vt, tag),
                              dict({"HV": hv, "X2": x2, "VTQ3": vt, "MODE": 0, "RFIX": f"{rc:.3f}"}, **extra)))
    return j


def g_ctran():
    allr, j = load(), []
    for hv in (150, 50):
        rc = _rc(allr, cname("trim", hv, 290, -3))
        if rc is None:
            print("skip ctran", hv); continue
        cls = ("22p", "100p") if hv == 150 else ("22p",)
        for cl in cls:
            j.append(make("sim7_chain_tran.cir", f"ctran_step_{hv}_{cl}", {"HV": hv, "RFIX": f"{rc:.3f}", "CL": cl, "MODEW": 0}))
            j.append(make("sim7_chain_tran.cir", f"ctran_sine_{hv}_{cl}", {"HV": hv, "RFIX": f"{rc:.3f}", "CL": cl, "MODEW": 1,
                                                                          "ACOD": 127 if hv == 150 else 45}))
    return j


def g_osc():
    """Follow-up on the U7/Q1 loop: which loads / values make it ring or limit-cycle."""
    j = []
    def both(tag, p):
        j.append(make("sim7_out_step.cir", f"osc_step_{tag}", p))
        j.append(make("sim7_out_loop.cir", f"osc_loop_{tag}", {k: v for k, v in p.items() if k != "VSTEP"}))
    for cl in ("22p", "33p"):
        both(f"150_{cl}", {"HV": 150, "VDC": 1.125, "CL": cl})
    for cl in ("47p", "100p"):
        both(f"150_{cl}_cgd20p", {"HV": 150, "VDC": 1.125, "CL": cl, "CGDMIN": "20p"})
        both(f"150_{cl}_r22_50", {"HV": 150, "VDC": 0.75, "CL": cl, "R22V": 50})
        both(f"50_{cl}", {"HV": 50, "VDC": 0.375, "CL": cl})
    for hv, vdc in ((150, 1.125), (50, 0.375)):                       # V1-like: no R31, load on TP5
        for cl in ("22p", "47p"):
            both(f"{hv}_{cl}_v1like", {"HV": hv, "VDC": vdc, "CL": cl, "R31V": 1})
    for rg in (47, 220):                                              # gate-stopper look (not on the board)
        both(f"150_100p_rg{rg}", {"HV": 150, "VDC": 1.125, "CL": "100p", "Rg": rg})
    return j


def g_osc2():
    """Crss-floor sensitivity at light loads, V1-like with a low Crss, and a compensation look.
    SUPERSEDED (not in sim7_results.json): like g_osc it runs WITH cshunt=1e-12, and group 'nocs'
    showed the with-cshunt limit cycles are a macro-model artefact, so no compensation is needed."""
    j = []
    def both(tag, p):
        j.append(make("sim7_out_step.cir", f"osc_step_{tag}", p))
        j.append(make("sim7_out_loop.cir", f"osc_loop_{tag}", {k: v for k, v in p.items() if k != "VSTEP"}))
    for cl in ("10p", "22p"):
        both(f"150_{cl}_cgd20p", {"HV": 150, "VDC": 1.125, "CL": cl, "CGDMIN": "20p"})
    for cl in ("22p", "47p"):
        both(f"150_{cl}_v1like_cgd20p", {"HV": 150, "VDC": 1.125, "CL": cl, "R31V": 1, "CGDMIN": "20p"})
    both("50_22p_cgd20p", {"HV": 50, "VDC": 0.375, "CL": "22p", "CGDMIN": "20p"})
    for rf, cf in (("1k", "100p"), ("1k", "220p"), ("2.2k", "100p")):
        for cl, cgd in (("10p", "50p"), ("100p", "50p"), ("10p", "20p"), ("100p", "20p")):
            both(f"150_{cl}_cgd{cgd}_rf{rf}_cf{cf}",
                 {"HV": 150, "VDC": 1.125, "CL": cl, "CGDMIN": cgd, "RF": rf, "CF": cf})
    return j


def g_nocs():
    """cshunt check.  The out_* templates inherit 'cshunt=1e-12' from Sim 2.  LTspice adds that 1 pF to
    EVERY node, including the ~50 internal nodes of the LM8261 macro-model (whose only explicit
    capacitor is its 8 pF Miller cap), which adds poles near the ~1 MHz loop crossover.  Sim 6 and the
    full-chain sim7_chain_tran.cir do not use it.  Re-run the stability cases without it to separate a
    model artefact from a real limit cycle."""
    j = []
    def both(tag, p):
        j.append(make("sim7_out_step.cir", f"nocs_step_{tag}", p, nocs=True))
        j.append(make("sim7_out_loop.cir", f"nocs_loop_{tag}", p, nocs=True))
    for hv, vdc in ((150, 0.15), (150, 1.125), (150, 2.1), (50, 0.375)):
        for cl in ("10p", "22p", "47p", "100p"):
            both(f"{hv}_{vdc}_{cl}", {"HV": hv, "VDC": vdc, "CL": cl})
    for cl in ("22p", "47p", "100p"):                                    # Crss-floor sensitivity
        both(f"150_1.125_{cl}_cgd20p", {"HV": 150, "VDC": 1.125, "CL": cl, "CGDMIN": "20p"})
    both("150_0.75_100p_r22_50", {"HV": 150, "VDC": 0.75, "CL": "100p", "R22V": 50})
    both("150_1.125_1n", {"HV": 150, "VDC": 1.125, "CL": "1n"})           # abuse case: ~10 m of coax
    for hv, cl in itertools.product((150, 50), ("10p", "22p", "47p", "100p")):
        j.append(make("sim7_out_sine.cir", f"nocs_sine_{hv}_{cl}", {"HV": hv, "CL": cl}, nocs=True))
    return j


GROUPS = dict(mon=g_mon, out=g_out, ls=g_ls, chain1=g_chain1, chain2=g_chain2, ctran=g_ctran, osc=g_osc,
              osc2=g_osc2, nocs=g_nocs)

if __name__ == "__main__":
    sel = sys.argv[1:] or list(GROUPS)
    for g in sel:
        if g.startswith("only:"):                 # only:<case-name-substring>,<group>[,<first opfix index>]
            parts = g[5:].split(",")
            sub, grp = parts[0], parts[1]
            jobs = [x for x in GROUPS[grp]() if sub in x["name"]]
            if len(parts) > 2:
                jobs = [make(x["template"], x["name"], x["params"], x["gear"], fix=int(parts[2]), nocs=x.get("nocs", False))
                        for x in jobs]
        else:
            jobs = GROUPS[g]()
        print(f"=== group {g}: {len(jobs)} cases", flush=True)
        save(run_all(jobs))
    print("done")
